@startuml

skinparam linetype ortho

!includesub village.puml!Main

package Context
{
    !startsub Main
    entity "Land | Участок " as Land {
    }
    !endsub

    struct "LandName | Название участка" as LandName {
    }

    struct "LandCadastreData | Кадастр участка" as LandCadastreData {
    }
} 

LandName ||--|| Land
LandCadastreData ||--|| Land

!includesub relations.puml!Land

@enduml