@startuml

skinparam linetype ortho
top to bottom direction

package Context
{
    !startsub Main
    entity "PersonIdentity | Лицо" as PersonIdentity {
    }
    !endsub

    struct "PersonContact | Контакт лица" as PersonContact {
    }

    struct "PersonIdentitySocialRating |  Социальный рейтинг" as PersonIdentitySocialRating {
    }
}

package Counterparty
{
    entity "PersonCounterparty | Паспорт лица" as PersonCounterparty {
    }


    struct "PersonRussianPassportIdentityDocument | Паспорт РФ" as PersonRussianPassportIdentityDocument
    {
    }

    struct "PersonForeignPassportIdentityDocument | Иностранный паспорт" as PersonForeignPassportIdentityDocument
    {
    }

    struct "PersonRussianBirthCertificateIdentityDocument | Свидетельство о рождении РФ" as PersonRussianBirthCertificateIdentityDocument
    {
    }

    struct "PersonRussianResidencePermitIdentityDocument | ВНЖ РФ" as PersonRussianResidencePermitIdentityDocument
    {
    }
}

PersonIdentity-[hidden]down-PersonCounterparty
PersonCounterparty-[hidden]down-PersonRussianPassportIdentityDocument
PersonRussianPassportIdentityDocument-[hidden]down-PersonForeignPassportIdentityDocument
PersonForeignPassportIdentityDocument-[hidden]down-PersonRussianBirthCertificateIdentityDocument
PersonRussianBirthCertificateIdentityDocument-[hidden]down-PersonRussianResidencePermitIdentityDocument

PersonContact }o--|| PersonIdentity
PersonIdentitySocialRating ||--|| PersonIdentity
PersonCounterparty ||--|| PersonIdentity
PersonRussianPassportIdentityDocument |o--|| PersonCounterparty
PersonForeignPassportIdentityDocument |o--|| PersonCounterparty
PersonRussianBirthCertificateIdentityDocument |o--|| PersonCounterparty
PersonRussianResidencePermitIdentityDocument |o--|| PersonCounterparty

@enduml