@startuml

skinparam linetype ortho
!includesub land.puml!Main

package Context
{
    !startsub Main
    entity "Посёлок / Village" as Village {
    }
    !endsub
}


!includesub relations.puml!Village

@enduml