= Автоплатежи
:page-toclevels: 4

== Enums
* state
** Active - Активный авто-платеж
** Pause - Приостановление авто-платежей


== (Новое) Создать автоплатёж
* POST mobile/autoPaymentSettings/v2

Не требует для создания автоплатежа переход в платёжный шлюз ПСБ.

Позволяет сделать автоплатёж на конкретный продукт лицевого счёта, если указан productId. Без productId происходит пополнение баланса. В зависимости от настроек лицевого счёта средства с баланса будут автоматически списаны на различные продукты при наличии незакрытых начислений.

psbCardId является обязательным и его следует брать из запроса получения банковских карт. Подробнее о банковских картах: xref:bankCard.adoc[]

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "contractId": 1,
    "productId": 2,
    "payPerMonth": 1000,
    "paymentDay" : 3,
    "useLastDayOfMonth" : false,
    "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
    "sendCheck": true,
    "emailNotification": "test@mail.ru",
    "phoneNumberNotification": "79998001122"
}
----
====


== (Устарело) Создать автоплатёж
* POST mobile/autoPaymentSettings

Предполагает возможность сделать автоплатёж на конкретный продукт лицевого счёта, если указан productId. Без productId происходит пополнение баланса. В зависимости от настроек лицевого счёта средства с баланса будут автоматически списаны на различные продукты при наличии незакрытых начислений.

psbCardId следует брать из запроса получения банковских карт. Подробнее о банковских картах: xref:bankCard.adoc[]

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "contractId": 1,
    "productId": 2,
    "payPerMonth": 1000,
    "paymentDay" : 3,
    "useLastDayOfMonth" : false,
    "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
    "sendCheck": true,
    "emailNotification": "test@mail.ru",
    "phoneNumberNotification": "79998001122"
}
----
====

=== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]


.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1, //номер заказа
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Хаб
Позволяет получить асинхронный ответ результата оплаты тестового платежа.

Хаб: *paymentHub*

Событие для подписки: *PsbRecurrentPaymentRegistration*

id события соответствует entityId из результата POST запроса на создание автоплатежа.

.JSON
[%collapsible]
====
[source,json]
----
{
  "id": 1,
  "isSuccess" : true 
}
----
====

== Отредактировать автоплатёж
Менять привязанную к автоплатёж банковскую карту нельзя. Можно только создать новый автоплатёж с другой картой.

=== Параметры запроса
* **id** - id автоплатежа

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "contractId": 1,
    "productId": 2,
    "payPerMonth": 1000,
    "paymentDay" : 3,
    "useLastDayOfMonth" : false,
    "sendCheck": true,
    "emailNotification": "test@mail.ru",
    "phoneNumberNotification": "79998001122"
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}
----
====


== Приостановить автоплатёж
* POST mobile/autoPaymentSettings/{id}/stop

=== Параметры запроса
* **id** - id автоплатежа

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}
----
====

== Возобновить автоплатёж
* POST mobile/autoPaymentSettings/{id}/resume

=== Параметры запроса
* **id** - id автоплатежа

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}
----
====

== Удалить автоплатёж
* DELETE mobile/autoPaymentSettings/{id}

=== Параметры запроса
* **id** - id автоплатежа

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Deleted"
  }
}
----
====

== Получить список моих автоплатежей
* GET mobile/autoPaymentSettings

=== Параметры запроса
* **states** - состояния автоплатежа. 
** Например: mobile/autoPaymentSettings?states=Active

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
    {
        "id": 1,
        "payPerMonth": 2500,
        "nextPayment": "2024-03-07T10:44:00.691",
        "paymentDay" : 3,
        "useLastDayOfMonth" : false,
        "state" : "Active",
        "land": {
            "id": 1769,
            "number": "29",
            "prefix": "А",
            "village": {
                "id": 2,
                "name": "Улыбка-2"
            }
        },
        "product" : {
            "id": 1,
            "name" : "Обслуживание"
        },
        "contract" : {
            "id": 1,
            "accountNumber" : "123456789"
        }

    }
]
----
====

== Получить карточку автоплатежа
* GET mobile/autoPaymentSettings/{id}

=== Параметры запроса
* **id** - id автоплатежа

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
    "id": 1,
    "payPerMonth": 2500,
    "nextPayment": "2024-03-07T10:44:00.691",
    "paymentDay" : 3,
    "useLastDayOfMonth" : false,
    "state" : "Active",
    "sendCheck": true,
    "emailNotification": "test@mail.ru",
    "phoneNumberNotification": "79998001122",
    "land": {
        "id": 1769,
        "number": "29",
        "prefix": "А",
        "village": {
            "id": 2,
            "name": "Улыбка-2"
        }
    },
    "product" : {
        "id": 1,
        "name" : "Обслуживание"
    },
    "contract" : {
        "id": 1,
        "name" : "Обслуживание посёлка 'Улыбка'",
        "accountNumber" : "123456789"
    },
    "bankCard" : {
        "id": 1,
        "number" : "7777XXXXXXXX1111"
    }
}
----
====


