= Банковские карты
:page-toclevels: 4

Банковская карта создаётся после успешной оплаты на 1 рубль через платёжный шлюз ПСБ


== (Новое) Добавить банковскую карту
* POST mobile/bankCards/v2

Добавляет банковскую карту в приложение через шлюз ПСБ.

После успешной оплаты на 1 рубль карта появляется в списке банковских карт.

=== Тело запроса
Отсутствует

=== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]


== Получить список банковских карт
* GET mobile/bankCards

=== Ответ
psbCardId нужен для использовании карты в автоплатежах ПСБ

.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "id": 1,
    "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
    "number": "7777XXXXXXXX1111",
    "isMain": true
  },
  {
    "id": 2,
    "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a6",
    "number": "1111XXXXXXXX7777",
    "isMain": false
  },
]
----
====


== Сделать банковскую карту основной
* POST mobile/bankCards/{id}/setAsMain

=== Параметры запроса
* **id** - id банковской карты

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}
----
====

== Удалить банковскую карту
* DELETE mobile/bankCards/{id}

=== Параметры запроса
* **id** - id банковской карты

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Deleted"
  }
}
----
====