= Платежи
:page-toclevels: 4


== Создание платежа с возможностью сохранения карты и создания автоплатежа
* POST mobile/payment/v3

Предполагает возможность при необходимости совместить обычную оплату, сохранение новой карты и создание автоплатежа по карте.



=== Пример варианта ответа с простым переходом по ссылке
Значение nextAction равно OpenUrl. Необходимо перейти по ссылке, чтобы попать в платежный шлюз (логика ЮКассы)

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "OpenUrl",
    "paymentGenerationLink" : "https://yoomoney.ru/checkout/payments/v2/contract?orderId=2ea9c294-000f-5000-8000-18aabf2cd0a8",
    "inputs" : []
  }
}
----
====

=== Пример варианта ответа со сборкой кнопки
Значение nextAction равно BuildButton. Необходимо собрать кнопку и имитировать нажатие на нее, чтобы перейти в платежный шлюз (логика ПСБ).

Смотрим подробнее о сборке кнопки здесь: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Пример варианта пустого правильного ответа
Не предполагает необходимость перехода по ссылке или сборки кнопки. Как правило, при таком ответе предполагается вызов эндпойнта создания автоплатежа (указано в описании конкретного кейса)

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}
----
====

=== События хаба

Следует отлавливать следующие события:

- PsbStatusChanged2 вместо PsbStatusChanged

- PsbBankCardRegistration2 вместо PsbBankCardRegistration

Старые события тоже могут приходить для обратной совместимости с предыдущей версией интернет-эквайринга. Их в новой версии отлавливать не надо


=== Кейс 1. Создание новой карты
Не требуется передавать данные оплаты.
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить 1 рубль (с возвратом)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : false,
    "saveNewCard" : true,
    "createAutoPayment" : false,
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки или ссылки на платежный шлюз.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Кейс 2. Обычная оплата
Требуется передавать данные оплаты.
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

Передавать psbCardId, если выбрана сохранённая существующая карта. Не передавать psbCardId, если выбрана новая карта без её сохранения.

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : false,
    "createAutoPayment" : false,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки или ссылки на платежный шлюз.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Кейс 3. Обычная оплата с созданием новой карты
Требуется передавать данные оплаты.
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

По результату оплаты будет также создана новая карта.

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : true,
    "createAutoPayment" : false,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки или ссылки на платежный шлюз.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Кейс 4. Обычная оплата с созданием автоплатежа
Требуется передавать данные оплаты.
Нельзя использовать при выборе "Новая карта" (psbCardId обязательное поле для передачи).
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

По результату оплаты следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : false,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки или ссылки на платежный шлюз.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====



=== Кейс 5. Обычная оплата с созданием новой карты и созданием автоплатежа
Требуется передавать данные оплаты.
Можно использовать только при выборе "Новая карта" (psbCardId должно быть null или отсутствовать).
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

По результату оплаты будет создана новая карта, дальше следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : true,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки или ссылки на платежный шлюз.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====



=== Кейс 6. Создание автоплатежа
Требуется передавать данные оплаты.
Нельзя использовать при выборе "Новая карта" (psbCardId обязательное поле для передачи).
Возвращает булевый результат, после чего следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : false,
    "saveNewCard" : false,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходит булевый результат.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}
----
====

=== Кейс 7. Создание автоплатежа с созданием новой карты
Требуется передавать данные оплаты.
Можно использовать только при выборе "Новая карта" (psbCardId должно быть null или отсутствовать).
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить 1 рубль (с возвратом)

По результату оплаты будет создана новая карта, дальше следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : false,
    "saveNewCard" : true,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки или ссылки на платежный шлюз.

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "nextAction" : "BuildButton",
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====