= Платежи
:page-toclevels: 4


== Создание платежа с возможностью сохранения карты и создания автоплатежа
* POST mobile/payment/v2

Предполагает возможность при необходимости совместить обычную оплату, сохранение новой карты и создание автоплатежа по карте.

=== Кейс 1. Создание новой карты
Не требуется передавать данные оплаты.
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить 1 рубль (с возвратом)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : false,
    "saveNewCard" : true,
    "createAutoPayment" : false,
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Кейс 2. Обычная оплата
Требуется передавать данные оплаты.
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

Передавать psbCardId, если выбрана сохранённая существующая карта. Не передавать psbCardId, если выбрана новая карта без её сохранения.

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : false,
    "createAutoPayment" : false,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Кейс 3. Обычная оплата с созданием новой карты
Требуется передавать данные оплаты.
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

По результату оплаты будет также создана новая карта.

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : true,
    "createAutoPayment" : false,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====

=== Кейс 4. Обычная оплата с созданием автоплатежа
Требуется передавать данные оплаты.
Нельзя использовать при выборе "Новая карта" (psbCardId обязательное поле для передачи).
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

По результату оплаты следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : false,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====



=== Кейс 5. Обычная оплата с созданием новой карты и созданием автоплатежа
Требуется передавать данные оплаты.
Можно использовать только при выборе "Новая карта" (psbCardId должно быть null или отсутствовать).
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить указанную сумму (без возврата)

По результату оплаты будет создана новая карта, дальше следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : true,
    "saveNewCard" : true,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====



=== Кейс 6. Создание автоплатежа
Требуется передавать данные оплаты.
Нельзя использовать при выборе "Новая карта" (psbCardId обязательное поле для передачи).
Возвращает булевый результат, после чего следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : false,
    "saveNewCard" : false,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходит булевый результат. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}
----
====

=== Кейс 7. Создание автоплатежа с созданием новой карты
Требуется передавать данные оплаты.
Можно использовать только при выборе "Новая карта" (psbCardId должно быть null или отсутствовать).
Возвращает данные для сборки кнопки редиректа на платёжный шлюз.
При переходе в платёжный шлюз нужно оплатить 1 рубль (с возвратом)

По результату оплаты будет создана новая карта, дальше следует вызвать эндпойнт создания автоплатежа (POST mobile/autoPaymentSettings/v2)

==== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "pay" : false,
    "saveNewCard" : true,
    "createAutoPayment" : true,
    "paymentSettings" : {
        "contractId": 1,
        "productId": 2,
        "amount": 1000,
        "sendCheck": true,
        "emailNotification": "test@mail.ru",
        "phoneNumberNotification": "79998001122"
    }
}
----
====

==== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====


== (УСТАРЕЛО) Создание платежа через ПСБ
* POST mobile/payment

Предполагает возможность сделать оплату на конкретный продукт лицевого счёта, если указан productId. Без productId происходит пополнение баланса. В зависимости от настроек лицевого счёта средства с баланса будут автоматически списаны на различные продукты при наличии незакрытых начислений.

psbCardId следует брать из запроса получения банковских карт. Подробнее о банковских картах: xref:bankCard.adoc[]

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "contractId": 1,
    "productId": 2,
    "amount": 1000,
    "psbCardId": "93842149-b0e1-11ee-8b19-f9150f8dc2a5",
    "sendCheck": true,
    "emailNotification": "test@mail.ru",
    "phoneNumberNotification": "79998001122"
}
----
====


=== Ответ
В payload ответа приходят данные для сборки кнопки редиректа на страницу ПСБ. Подробнее: xref:psb.adoc[]

.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": 1,
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  },
  "payload" : {
    "paymentGenerationLink" : "https://3ds.payment.ru/cgi-bin/cgi_link",
    "inputs" : [
        {
            "key" : "key1",
            "value" : "value1"
        },
        {
            "key" : "key2",
            "value" : "value2"
        }
    ]
  }
}
----
====
