= Аккаунт
:page-toclevels: 4

== Enums
* state
** NotCreated - Не создан
** Created - Создан
** Invited - Приглашен
** Activated - Активирован


== Проверить наличие лицевых счетов
* GET web/person/{id}/checkContracts

=== Параметры запроса
* **id** - id лица

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "hasAnyContracts" : true 
}
----
====

== Создать аккаунт
* POST web/account/v2/create

Создает аккаунт мобильного приложения для лица на выбранный телефон, который служит ему логином

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "personId": 1,
    "login": "79161112233"
}
----
====

== Отправить приглашение
* POST web/account/v2/invite

Отправить приглашение лицу для входа в его мобильный аккаунт

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "personId": 1,
    "text" : "Здравствуйте. Компания Инвест-сервис предоставила доступ к вашему личному кабинету. Скачайте приложение - https://loklink.ru/ZtpIUCW"
}
----
====

== (УСТАРЕЛО) Получить текст приглашения
* GET web/account/v2/inviteText

Получить текст приглашения со ссылкой на приложение

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
    "text": "Здравствуйте. Компания Инвест-сервис предоставила доступ к вашему личному кабинету. Скачайте приложение - ссылка"
}
----
====

== Получить список текстов приглашений для брендов
* GET web/account/v2/inviteTexts

Получить список текстов приглашений для брендов

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "text": "Здравствуйте. Компания Инвест-сервис предоставила доступ к вашему личному кабинету. Скачайте приложение - https://loklink.ru/ZtpIUCW",
    "brand": "Инвест",
    "id": 1
  },
  {
    "text": "Здравствуйте. Компания М2о2 предоставила доступ к вашему личному кабинету. Скачайте приложение - https://loklink.ru/ZtpIUCW",
    "brand": "М2о2",
    "id": 2
  }
]
----
====

== Изменить логин
* POST web/account/v2/changeLogin

Изменить логин мобильного аккаунта лица

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "personId": 1,
    "newLogin" : "79251112233"
}
----
====

== Удалить аккаунт
* POST web/account/v2/delete

Удаляет аккаунт мобильного приложения у лица

=== Тело запроса
.JSON
[%collapsible]
====
[source,json]
----
{
    "personId": 1
}
----
====