= Оповещения
:page-toclevels: 4

http://api.stage.lokeodata.ru:5002/swagger/index.html?urls.primaryName=Main%20Web%20API[Сваггер] (секция Notifications)


== Enums
* publicationState
** Created - Создано
** ReadyToPublish - Готово к публикации (статус после редактирования оповещения)** ReadyToBeSent - Готово к отправке (статус после немедленной публикации)
** Scheduled - Добавлено в расписание (статус после отложенной публикации)
** InProgress - В процессе публикации (статус при взятии оповещения системой из очереди на публикацию)
** Published - Опубликовано


* publicationType
** MobileAccount - Личный кабинет (Новость)
** Email - Электронная почта
** Sms - СМС
** OwnershipReport - Рассылка по собственности

* emailStatus
** Queued - Принято в очередь
** Sent - Отправлено
** Delivered - Доставлено
** Skipped - Не отправлено 
** SoftBounced - Сообщение не доставлено
** HardBounced - Сообщение не может быть доставлено

* smsStatus
** Enqueued - В очереди на отправление
** Accepted - Принято к отправлению
** Delivered - Доставлено
** NonDelivered - Отклонено
** Scheduled - Запланировано
** Canceled - Отменено
** Wait - Ожидает
** Overdue - Просрочено

* entityStatus (используется для фильтрация архивированных)
** Created - Создано (если не в архиве)
** Archived - Архивировано


== Хаб для получение статусов оповещений
* notificationHub

=== NotificationPublicationStateChanged
id - Id оповещения
publicationState - Статус публикации

=== NotificationInvoicesGenerated
id - Id оповещения

== Создание новости
* POST web/notifications/news

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "name": "Тестовая новость",
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}

----
====

== Создание оповещения по email
* POST web/notifications/email

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "name": "Тестовая новость",
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}

----
====

== Создание оповещения по sms
* POST web/notifications/sms

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "name": "Тестовая новость",
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}

----
====

== Создание оповещения для рассылки по собственности
* POST web/notifications/ownership

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "name": "Тестовая рассылка за август",
  "period": "2024-08-01T00:00:00.000Z"
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Created"
  }
}

----
====

== Редактирование новости
* POST web/notifications/news/edit
* Можно редактировать при статусе Created или ReadyToPublish
* Меняет статус на ReadyToPublish

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "title": "Тестовый заголовок",
  "text": "Тестовый текст",
  "tags": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "files": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "photos": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "publicationSettings": {
    "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
    ],
    "pinWhenPublishing": true
  }
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}

----
====

== Редактирование оповещения по email
* POST web/notifications/email/edit
* Можно редактировать при статусе Created или ReadyToPublish
* Меняет статус на ReadyToPublish

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "title": "Тестовый заголовок",
  "text": "Тестовый текст",
  "files": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "photos": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "publicationSettings": {
    "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
    ],
    "notifyOwners": true,
    "notifyRepresentatives": true
  }
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}

----
====

== Редактирование оповещения по sms
* POST web/notifications/sms/edit
* Можно редактировать при статусе Created или ReadyToPublish
* Меняет статус на ReadyToPublish

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "title": "Тестовый заголовок",
  "text": "Тестовый текст",
  "publicationSettings": {
    "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
    ],
    "notifyOwners": true,
    "notifyRepresentatives": true
  }
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}

----
====

== Редактирование оповещения для рассылки по собственности
* POST web/notifications/ownership/edit
* Можно редактировать при статусе Created или ReadyToPublish
* Меняет статус на ReadyToPublish

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "title": "Тестовый заголовок рассылки",
  "publicationSettings": {
    "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
    ]
  }
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "Updated"
  }
}

----
====

== Генерация квитанций для рассылки по собственности
* POST web/notifications/ownership/generate
* Генерация происходит в фоновом режиме, следует подписаться на notificationHub на событие NotificationInvoicesGenerated, которое сигнализирует об окончании генерации
* Нельзя генерировать квитанции повторно, если hasInvoices в карточке оповещения == true

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "entityId": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": "InProgress"
  }
}

----
====

== Получение количества получателей для новости
* POST web/notifications/news/receivers - использовать в режиме создания/редактирования оповещения

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
  ]
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": null
  },
  "payload": {
    "count": 1
  }
}

----
====

== Получение количества получателей для email
* POST web/notifications/email/receivers - использовать в режиме создания/редактирования оповещения

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "notifyOwners": true,
  "notifyRepresentatives": true,
  "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
  ]
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": null
  },
  "payload": {
    "count": 1
  }
}

----
====

== Получение количества получателей для sms
* POST web/notifications/sms/receivers - использовать в режиме создания/редактирования оповещения

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "notifyOwners": true,
  "notifyRepresentatives": true,
  "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
  ]
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": null
  },
  "payload": {
    "count": 1
  }
}

----
====

== Получение количества получателей для рассылки собственности
* POST web/notifications/ownership/receivers - использовать в режиме создания/редактирования оповещения

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "lands": [
      {
        "id": 9538
      },
      {
        "id": 10099
      }
  ]
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "result": {
    "isSuccess": true,
    "errorCode": null,
    "errorDescription": null,
    "commandState": null
  },
  "payload": {
    "count": 1
  }
}

----
====

== Получение списка шаблонов контента
* GET web/notifications/templates

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "name": "Тестовое название",
    "title": "Тестовый заголовок",
    "text": "Тестовый текст",
    "id": "08235eb7-c08a-49f0-afff-4c7bd62c24f9"
  },
  {
    "name": "Тестовое название 2",
    "title": "Тестовый заголовок 2",
    "text": "Тестовый текст 2",
    "id": "08235eb7-c08a-49f0-afff-4c7bd62c24f8"
  },
]

----
====

== Получение списка тегов для оповещений
* GET web/notifications/tags

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "name": "Новости посёлка",
    "id": "08235eb7-c08a-49f0-afff-4c7bd62c24f9"
  },
  {
    "name": "Водоснабжение",
    "id": "30ba04b4-d555-41ef-ab88-0116bb62b8cd"
  },
  {
    "name": "Ремонт дорог",
    "id": "418a2cd0-2b02-4cf0-92ab-35e10fd321d2"
  },
  {
    "name": "Управляющая компания",
    "id": "591ad90b-7e6b-4e5b-b944-918254f067e1"
  },
  {
    "name": "Обслуживание",
    "id": "69baa4b8-d8d7-4685-ac47-182583be238b"
  },
  {
    "name": "Объявления",
    "id": "bb5c5975-4941-4848-a789-92d281714a6d"
  }
]
----
====

== Получение списка оповещений
* GET web/notifications

=== Параметры запроса
* **publicationTypes** - тип публикации
** Например: web/notifications?publicationTypes=Email,Sms
* **entityStatus** - статус сущности (архивировано или нет)
** Например: web/notifications?entityStatus=Created,Archived (забираем все)

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "name": "Тестовая новость",
    "receiverCount": 2,
    "publicationDate": "2024-03-29T12:34:12.023",
    "publicationState": "InProgress",
    "pinned": true,
    "publicationSettings": {
      "publicationType": "MobileAccount",
      "id": "08dc4fd3-6466-4068-8df5-c8619a9a91e6"
    },
    "isDeleted" : false,
    "id": "08dc4fd3-645d-4e2d-8472-33e8a94cbfde"
  }
]
----
====

== Получение карточки оповещения
* GET web/notifications/{id}

=== Параметры запроса
* **id** - id новости
** Например: mobile/news/08dc4fda-bc16-4c75-8912-f5cf488f79dc

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
{
  "id": "08dc4fda-a16c-4c4f-8558-70906c5ceef6",
  "name": "Тестовая новость",
  "title": "Тестовый заголовок",
  "text": "Тестовый текст",
  "pinned" : true,
  "hasInvoices" : true,
  "isDeleted" : false,
  "tags": [
    {
      "id": "08dc4fda-a17f-4f3b-89e8-080f9f6d2a2d",
      "name": "Новости посёлка"
    }
  ],
  "files": [
        {
          "id": "08dc4fda-a17f-4f3b-89e8-080f9f6d2a2d",
          "name": "Чудо Град.xml",
          "publicPath" : "https://s3.yandexcloud.net/lokeo-dev/cadastralPlans/08db98c4-948a-4aef-89ad-065c20cf9db7-Чудо Град.xml"
        }
    ],
  "photos": [
        {
          "id": "08dc4fda-a17f-4f3b-89e8-080f9f6d2a2d",
          "name": "Чудо Град.png",
          "publicPath" : "https://s3.yandexcloud.net/lokeo-dev/cadastralPlans/08db98c4-948a-4aef-89ad-065c20cf9db7-Чудо Град.png"
        }
    ],
  "publicationSettings": {
    "id": "08dc4fda-a176-48e8-8da9-fe118427e713",
    "lands": [
      {
        "id": 9538,
        "mainLandVersion": {
          "id": 9539,
          "prefix": null,
          "number": "29"
        },
        "village": {
          "id": 2,
          "name": "КП «СОСНОВЫЙ БЕРЕГ»"
        }
      },
      {
        "id": 10099,
        "mainLandVersion": {
          "id": 10103,
          "prefix": null,
          "number": "80"
        },
        "village": {
          "id": 1,
          "name": "Калинка-Малинка"
        }
      }
    ],
    "notifyOwners": true,
    "notifyRepresentatives": true,
    "pinWhenPublishing": true,
    "delayPublication": true,
    "delayedPublicationDate": "2024-03-29T11:49:07.946Z"
  }
}
----
====


== Получение списка получателей для драйвера оповещения
* GET web/notifications/{id}/receivers

=== Параметры запроса
* **id** - id оповещения
* **landIds** - id участка
** Например: web/notifications/{id}/receivers?landIds=1,2
* **tagIds** - id тега
** Например: web/notifications/{id}/receivers?tagIds=08dc4fd3-6466-4068-8df5-c8619a9a91e6
* **searchTerm** - поиск по номеру участка
** Например: web/notifications/{id}/receivers?searchTerm=3 Улыбка

=== Ответ (Новость)
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "id" : "08dc4fda-a176-48e8-8da9-fe118427e713",
    "hasAccount" : true,
    "canBeNotified" : true,
    "title" : "Тестовый заголовок",
    "text" : "Тестовое сообщение",
    "sent" : true,
    "delivered" : true,
    "read" : true,
    "person" : {
        "id" : 1,
        "firstName" : "Иван",
        "middleName" : "Иван",
        "lastName" : "Иван"
    },
    "lands" : [
      {
        "land" : {
          "mainLandVersion" : {
            "id" : 1,
            "prefix" : "А",
            "number" : "3"
          },
          "village" : {
              "id" : 1,
              "name" : "Улыбка"
          },
        }
      }
    ]
  }
]
----
====

=== Ответ (Email)
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "id" : "08dc4fda-a176-48e8-8da9-fe118427e713",
    "hasAccount" : true,
    "canBeNotified" : true,
    "title" : "Тестовый заголовок",
    "text" : "Тестовое сообщение",
    "sent" : true,
    "delivered" : true,
    "read" : true,
    "person" : {
        "id" : 1,
        "firstName" : "Иван",
        "middleName" : "Иван",
        "lastName" : "Иван"
    },
    "lands" : [
      {
        "land" : {
          "mainLandVersion" : {
            "id" : 1,
            "prefix" : "А",
            "number" : "3"
          },
          "village" : {
              "id" : 1,
              "name" : "Улыбка"
          },
        }
      }
    ],
    "emailStatus" : {
        "hasEmail" : true,
        "isMainNotifier" : true,
        "email" : "test@mail.ru",
        "status" : "Delivered",
        "open" : true,
        "redirect" : false,
        "spam" : false,
        "unsubscribe" : false
    }
  }
]
----
====

=== Ответ (Sms)
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "id" : "08dc4fda-a176-48e8-8da9-fe118427e713",
    "hasAccount" : true,
    "canBeNotified" : true,
    "title" : "Тестовый заголовок",
    "text" : "Тестовое сообщение",
    "sent" : true,
    "delivered" : true,
    "read" : true,
    "person" : {
        "id" : 1,
        "firstName" : "Иван",
        "middleName" : "Иван",
        "lastName" : "Иван"
    },
    "lands" : [
      {
        "land" : {
          "mainLandVersion" : {
            "id" : 1,
            "prefix" : "А",
            "number" : "3"
          },
          "village" : {
              "id" : 1,
              "name" : "Улыбка"
          },
        }
      }
    ],
    "smsStatus" : {
        "hasPhoneNumber" : true,
        "isMainNotifier" : true,
        "phone" : "79007001122",
        "price" : 1.00,
        "status" : "Delivered"
    }
  }
]
----
====

=== Ответ (Рассылка по собственности)
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "id" : "08dc4fda-a176-48e8-8da9-fe118427e713",
    "hasAccount" : true,
    "canBeNotified" : true,
    "title" : "Тестовый заголовок",
    "text" : "Тестовое сообщение",
    "sent" : true,
    "delivered" : true,
    "read" : true,
    "person" : {
        "id" : 1,
        "firstName" : "Иван",
        "middleName" : "Иван",
        "lastName" : "Иван"
    },
    "lands" : [
      {
        "land" : {
          "mainLandVersion" : {
            "id" : 1,
            "prefix" : "А",
            "number" : "3"
          },
          "village" : {
              "id" : 1,
              "name" : "Улыбка"
          },
        }
      }
    ],
    "emailStatus" : {
        "hasEmail" : true,
        "isMainNotifier" : true,
        "email" : "test@mail.ru",
        "status" : "Delivered",
        "open" : true,
        "redirect" : false,
        "spam" : false,
        "unsubscribe" : false
    },
    "ownershipReport" : {
        "contractInvoices" : [
          {
            "link" : "https://test.link1",
            "contract" : {
              "name" : "Договор о порядке пользования объектами инфраструктуры и обслуживания садового поселка лицевого счёта ЛП",
              "contractNumber": "ЛП №41",
              "id": 18
            }
          },
          {
            "link" : "https://test.link2",
            "contract" : {
              "name" : "Договор о порядке пользования объектами инфраструктуры и обслуживания садового поселка лицевого счёта ЛП",
              "contractNumber": "ЛП №42",
              "id": 19
            }
          }
        ]
    }
  }
]
----
====

== Получение текста сообщения для получателя
* GET web/receivers/{id}/text

=== Параметры запроса
* **id** - id получателя (берётся из родительского id получателя из списка получателей)

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "title" : "Тестовый заголовок",
    "text" : "Тестовое сообщение",
  }
]
----
====

== Отправить сообщение получателю
* POST web/receivers/{id}/sendMessage

=== Параметры запроса
* **id** - id получателя (берётся из родительского id получателя из списка получателей)

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "entityId" : "08dc4fda-a176-48e8-8da9-fe118427e713",
      "isSuccess" : true,
      "commandState" : "Updated"
    }
  }
]
----
====


== Публикация оповещения
* POST web/notifications/{id}/publish
* Можно публиковать при статусе ReadyToPublish или Scheduled (для смены времени публикации)
* Внимание! Если тип оповещения является рассылкой по собственности, то опубликовать можно только оповещения с hasInvoices == true
* Меняет статус на Scheduled или ReadyToBeSent

=== Параметры запроса
* **id** - id оповещения


=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "delayPublication": true,
  "delayedPublicationDate": "2024-03-29T11:49:07.946Z"
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "entityId" : "08dc4fda-a176-48e8-8da9-fe118427e713",
      "isSuccess" : true,
      "commandState" : "Updated"
    }
  }
]
----
====

== Снятие с публикации оповещения
* POST web/notifications/{id}/unpublish
* Можно снимать с публикации при статусе Scheduled
* Возвращает на статус ReadyToPublish

=== Параметры запроса
* **id** - id оповещения

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "entityId" : "08dc4fda-a176-48e8-8da9-fe118427e713",
      "isSuccess" : true,
      "commandState" : "Updated"
    }
  }
]
----
====


== Архивация оповещения
* DELETE web/notifications/{id}/archive
* Можно архивировать при статусе Published

=== Параметры запроса
* **id** - id оповещения

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "entityId" : "08dc4fda-a176-48e8-8da9-fe118427e713",
      "isSuccess" : true,
      "commandState" : "Archived"
    }
  }
]
----
====


== Восстановление из архива оповещения
* POST web/notifications/{id}/restore
* Можно восстановить при isDeleted

=== Параметры запроса
* **id** - id оповещения

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "entityId" : "08dc4fda-a176-48e8-8da9-fe118427e713",
      "isSuccess" : true,
      "commandState" : "Updated"
    }
  }
]
----
====

== Удаление оповещения
* DELETE web/notifications/{id}
* Можно удалять при статусе Created или ReadyToPublish

=== Параметры запроса
* **id** - id оповещения

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "entityId" : "08dc4fda-a176-48e8-8da9-fe118427e713",
      "isSuccess" : true,
      "commandState" : "Deleted"
    }
  }
]
----
====

== Отправка тестового письма
* POST web/notifications/{id}/email/test

=== Параметры запроса
* **id** - id оповещения

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "email": "test@mail.ru",
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "isSuccess" : true,
      "commandState" : "Updated"
    }
  }
]
----
====

== Отправка тестового sms
* POST web/notifications/{id}/sms/test

=== Параметры запроса
* **id** - id оповещения

=== Запрос
.JSON
[%collapsible]
====
[source,json]
----
{
  "sms": "79161112233",
}
----
====

=== Ответ
.JSON
[%collapsible]
====
[source,json]
----
[
  {
    "result" : {
      "isSuccess" : true,
      "commandState" : "Updated"
    }
  }
]
----
====



